PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
baseURL = "https://1903test.netlify.app/"
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = true
contentDir = "content"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
paginate = 10
publishDir = "public"
rssLimit = 10
theme = "hello-friend-ng"
title = "1903 Analytics and Consulting"
[author]
name = "Jane Doe"
[blackfriday]
hrefTargetBlank = true
[languages.en]
copyright = "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
weight = 1
[languages.fr]
copyright = "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
weight = 2
[params]
customCSS = []
customJS = []
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"
description = "Nice theme for homepages and blogs"
disableReadOtherPosts = false
enableGlobalLanguageMenu = false
enableSharingButtons = true
enableThemeToggle = false
homeSubtitle = "Data Science. Data Analytics. Programming Courses."
images = [""]
justifyContent = false
keywords = ""
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"
[params.footer]
author = false
bottomText = []
copyright = false
rss = false
topText = []
trademark = false
[params.logo]
logoCursorColor = "#67a2c9"
logoHomeLink = "/"
logoMark = ">"
logoText = "$ cd /home/"
[params.portrait]
alt = "Portrait"
maxWidth = "150px"
path = "images/code-solid.svg"
[[params.social]]
name = "email"
url = "mailto:nobody@example.com"
[[params.social]]
name = "github"
url = "https://github.com/"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/"
[permalinks]
posts = "/posts/:year/:month/:title/"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
